// グローバル状態管理オブジェクト
export const state = {
  // --- テーブルデータ ---
  cmfTable: null,
  osTable: null,
  dTable: null,
  dTableOPP: null,
  rTable: null,

  // --- 画像 ---
  img: null,
  img2: null,

  // --- DOM要素 ---
  polarizerSelect: null,
  cellophaneAddButton: null,
  cellophaneRemoveButton: null,
  slider: null,
  lineradio: null,
  optRadio: null,
  edgieSlider: null,
  sliderCluster: null,
  inputCluster: null,
  cmd: null,
  radio: null,
  Intensity_slider: null,
  graphParent: null,

  // --- テーブルから取得したデータ ---
  cmfRowNum: 0,
  osRowNum: 0,
  dRowNum: 0,
  waveLengthArr: [],
  xLambda: [],
  yLambda: [],
  zLambda: [],
  osArr: [],
  osArrOrigin: [],
  dArr: [],
  R_all: [],
  R_os: [],
  Intensity_all_box: [],
  speyBox: [],

  // --- XYZ刺激値配列 ---
  xArrAfter: [],
  yArrAfter: [],
  zArrAfter: [],
  xArrBefore: [],
  yArrBefore: [],
  zArrBefore: [],
  sum_ls_xArrAfter: 0,
  sum_ls_yArrAfter: 0,
  sum_ls_zArrAfter: 0,

  // --- RGB値 ---
  rBefore: 0,
  gBefore: 0,
  bBefore: 0,
  rAfter: 0,
  gAfter: 0,
  bAfter: 0,
  rAfter1: 0,
  gAfter1: 0,
  bAfter1: 0,
  rAfter2: 0,
  gAfter2: 0,
  bAfter2: 0,

  // --- セロハン ---
  cellophaneNum: 0,
  cellophaneArr: [],
  colabNum: 0,
  precolabNum: 0,
  rAftera: null,
  gAftera: null,
  bAftera: null,

  // --- ジオメトリ ---
  centerX: 0,
  centerY: 0,
  x1: 0,
  x2: 0,
  x3: 0,
  x4: 0,
  y1: 0,
  y2: 0,
  y3: 0,
  y4: 0,
  tape_angle_get: 0,
  radius: 111,
  angle_1: 0,
  angle_2: 0,
  angle_3: 0,
  angle_4: 0,
  tape_angle: [],
  tape_angle_cal: [],
  tape_number_cal: [],

  // --- 分割描画 ---
  count2: 0,
  lastValue: undefined,
  BisDead: false,
  CisDead: false,
  DrawisDead: false,
  Bcount: 0,
  Bsize: undefined,
  Bdraw: 0,
  drawT: 0,
  drawSize: 0,
  drawCount: 0,
  tape_array: null,
  tape_arraySum: null,
  zz: 0,
  last_otherCellophaneNums: new Array(14).fill(1),
  last_targetAngles: new Array(14).fill(1),
  last_opt: new Array(14).fill(1),
  last_polarizer: null,
  rotateTime: 0,
  calculate: 0,

  // --- クラスター分類 ---
  clusters: 4,
  clusterColors: [],
  labels: [],
  edgePixels: [],
  n: 3,
  iterations: 3,
  dilationSize: 2,
  lastCluster: undefined,
  copyimg: null,
  clusterCount: 0,
  clusterCount1: 0,
  rAfterak: null,
  gAfterak: null,
  bAfterak: null,
  rotateInputV: null,
  Cluster1isDead: false,
  changeisDead: false,
  thresholds: null,
  lasthreshold: null,

  // --- HSV色空間 ---
  hAfter1: 0,
  sAfter1: 0,
  vAfter1: 0,
  hAfter2: 0,
  sAfter2: 0,
  vAfter2: 0,
  hAfterak: null,
  sAfterak: null,
  vAfterak: null,
  x_1: 0,
  y_1: 0,
  xdata: [],
  ydata: [],

  // --- 光強度 ---
  Intensity_all: 0,
  Intensity_all_now: 0,
  K: 0,
  spey: 0,

  // --- optRadio状態 ---
  currentValue: null,
  preValue: null,
  currentSlider: null,
  lastSlider: null,

  // --- Chart ---
  mainChartObj: undefined,
  subChartObj: undefined,
};
